version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.9.16
        commands:
            - pip install --upgrade pip
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/aira/*.py
            - pylint $CODEBUILD_SRC_DIR/aira/aira/*.py
            - pylint --disable=C0103,E1101,R0903 $CODEBUILD_SRC_DIR/aira/appaira/*.py
artifacts:
    files:
        - '**/*'