# Generated by Django 4.2.10 on 2024-04-06 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='addtocart', to=settings.AUTH_USER_MODEL),
        ),
    ]
